config/routes.rb
Ontime::Application.routes.draw do
  devise_for :users
   resources :deadlines
  authenticated :user do
     root :to => "deadlines#index", :as => "authenticated_root"
  
  end
  root "welcome#home"
 

end

app/models/deadline.rb
class Deadline < ActiveRecord::Base

	validates :title, presence: true,
				length: { minimum: 8 }


	validates :date, presence: true

	validates :description, presence: true,
				length: { maximum: 230 }

   #validates_format_of :date, :with => /\A[0-9]{4}-[0-1][0-9]-[0-3][0-9]\z/, :message => "Enter Date in this format: YYYY-MM-DD" 
	belongs_to :user	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable
          has_many :deadlines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/deadlines_controller.rb
class DeadlinesController < ApplicationController

	def new
		@deadline = current_user.deadlines.new
	end

	def create
		@deadline = current_user.deadlines.new(params[:deadline].permit(:title, :date, :description))
		if @deadline.save
			redirect_to @deadline
		else
			render 'new'
		end
	end

	def show
		@deadline = Deadline.find(params[:id])
	end

	def edit
		@deadline = current_user.deadlines.find(params[:id])
	end

	def index
		
		@deadlines = current_user.deadlines.all
		@deadlines = current_user.deadlines.order(:date).paginate(:page => params[:page], :per_page => 5)
	end

	def update
		@deadline = current_user.deadlines.find(params[:id])

		if @deadline.update(params[:deadline].permit(:title, :date, :description))
			redirect_to @deadline
		else
			render 'edit'
		end
	end

	def destroy
		@deadline = current_user.deadlines.find(params[:id])
		@deadline.destroy

		redirect_to deadlines_path

	end

	private
	def post_params
		params.require(:deadline).permit(:title, :date, :description)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deadlines/edit.html.erb
<center><h1> Edit deadline </h1></center>
<%= simple_form_for @deadline, html: { class: "form-horizontal"}, :url => url_for(:action => 'update', controller => 'deadline'),
:method => 'patch' do |f| %>
   <%= f.error_notification %>

  <%=f.input :title %>
  <%=f.input :date, as: :string, input_html: {:id => "datetimepicker"}%>
  <%= f.input :description, as: :text, input_html: {rows: "6"} %>
    

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>

<% end %>

<%= link_to "Back", deadlines_path, :class =>'btn btn-primary'  %>

app/views/deadlines/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="js/TimeCircles.js"></script>
    <script type="text/javascript" src="js/TimeCircles.js"></script>
    
        <link rel="stylesheet" href="css/TimeCircles.css" />
        
        <link rel="stylesheet" href="css/TimeCircles.css" />
   
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        
    <title>Track Deadlines</title>
        
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Custom CSS for the 'Thumbnail Gallery' Template -->
    <link href="css/2-col-portfolio.css" rel="stylesheet">
</head>

<body>
<body background="img/wild_oliva.png">

   
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Deadline CountDown', root_path, :class => "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Edit Profile", edit_user_registration_path %>
                   <li><%= link_to "Log-out", destroy_user_session_path, method: :delete%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Deadline Countdown
                    <small>Stay on track with all your projects</small>
                </h1>
            </div>
            <%= link_to "New Deadline", new_deadline_path, :class => 'btn btn-success'%>
        </div>

        <div class="row">

    <table>
        <% @deadlines.each do |deadline| %>
        <tr>
            <td><div class="col-lg-6 col-md-6 portfolio-item">
                
                    <div id="circle">
                        <div class="DateCountdown" data-date=<%= deadline.date %> style="width: 100%;"></div>

                    </div>
                </a> 
                     <script>
        $(".DateCountdown").TimeCircles({
    "animation": "smooth",
    "bg_width": 0.3,
    "fg_width": 0.03333333333333333,
    "circle_bg_color": "#90989F",
    "time": {
        "Days": {
            "text": "Days",
            "color": "#d23419",
            "show": true
        },
        "Hours": {
            "text": "Hours",
            "color": "#46c871",
            "show": true
        },
        "Minutes": {
            "text": "Minutes",
            "color": "#6698ea",
            "show": true
        },
        "Seconds": {
            "text": "Seconds",
            "color": "#d537f1",
            "show": true
        }
    }
});

     </script>  
            </div></td>
            
            <td>
                
                <td><h3><%= deadline.title %></h3>
                  Description:  <%= deadline.description %><br><%= link_to 'delete', deadline_path(deadline),
                method: :delete, data: { confirm: 'are your sure'}, :class =>'btn btn-info' %>
                <%= link_to 'Edit', edit_deadline_path(deadline), :class =>'btn btn-info' %></td>
              </td>
        </tr>
        <% end %>


    </table>


        </div>
       
    <center><%= will_paginate @deadlines, renderer: BootstrapPagination::Rails %></center>


    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

</body>

</html>

app/views/deadlines/new.html.erb
<center><h1> New deadline </h1></center>
<%= simple_form_for(@deadline, url: deadlines_path, html: { class: "form-horizontal"}) do |f| %>
   <%= f.error_notification %>

  <%=f.input :title %>
  <%=f.input :date, as: :string, input_html: {:id => "datetimepicker"}%>
  <%= f.input :description, as: :text, input_html: {rows: "6"} %>
    

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>

<% end %>

<%= link_to "Back", deadlines_path, :class =>'btn btn-primary'  %>

app/views/deadlines/show.html.erb
<!DOCTYPE html>
<html lang="en">



<head>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="/js/TimeCircles.js"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <script type="text/javascript" src="/js/TimeCircles.js"></script>
    
        <link rel="stylesheet" href="/css/TimeCircles.css" />
   
        
        
        
</head>
<body>
	<br>
    <br>
<center><p>
	<strong>Title:</strong>
	<%= @deadline.title %>
</p><center>

<center><p>
	<strong>Date:</strong>
	<%= @deadline.date %>
</p><center>

<center><p style="margin-left:5em;">
	<strong>Description:</strong>
	<%= @deadline.description %>
</p><center>
<div id="circle">
   <div class="DateCountdown" data-date=<%= @deadline.date %> style="width: 100%;"></div>

   <script>
        $(".DateCountdown").TimeCircles({
    "animation": "smooth",
    "bg_width": 0.3,
    "fg_width": 0.03333333333333333,
    "circle_bg_color": "#90989F",
    "time": {
        "Days": {
            "text": "Days",
            "color": "#d23419",
            "show": true
        },
        "Hours": {
            "text": "Hours",
            "color": "#46c871",
            "show": true
        },
        "Minutes": {
            "text": "Minutes",
            "color": "#6698ea",
            "show": true
        },
        "Seconds": {
            "text": "Seconds",
            "color": "#d537f1",
            "show": true
        }
    }
});

     </script> 
     </div>
     <br>
<%= link_to "Back", deadlines_path, :class =>'btn btn-primary' %>
</body>
</html>

app/views/layouts/_deadline.html.erb
<link rel="stylesheet" type="text/css" href="/css/jquery.datetimepicker.css" />
<script src="/js/jquery.js"></script>
<script src="/js/jquery.datetimepicker.js"></script>

<script>
$('#datetimepicker').datetimepicker();
</script>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Simple Deadline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/laptop.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand nav-link" href=<%=root_path%>>Deadline CountDown</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %>
            <li><%= link_to "Log-out", destroy_user_session_path, method: :delete%> 
              <% else %>
            <li><%= link_to "Log-In", new_user_session_path %>
            
            <% end %>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Deadline</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert #{name}") %>
	<% end %>
	

<%= yield %>

</body>
<%= render 'layouts/deadline' %>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Track Dadlines</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/laptop.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <a class="navbar-brand nav-link" href=<%=root_path%>>Deadline CountDown</a>
        </div> <!-- /.navbar-header -->

        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %>
            <li><%= link_to "Log-out", destroy_user_session_path, method: :delete%> 
              <% else %>
            <li><%= link_to "Log-In", new_user_session_path %>
            
            <% end %>
          </ul>
        </div> <!-- /.navbar-collapse -->
      </div> <!-- /.container -->
    </nav> <!-- /.navbar -->

    <div id="top" class="jumbotron">
      <div class="container">
        <h1>Track Deadlines Easily</h1>
        <%= link_to "Sign Up Now" , new_user_registration_path, class: "btn btn-primary btn-large" %>
        <br></br>
        <div id="macbook">
          <div id="tour" class="carousel slide">
            <ol class="carousel-indicators">
              <li data-target="#tour" data-slide-to="0" class="active"></li>
              <li data-target="#tour" data-slide-to="1"></li>
              <li data-target="#tour" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">
              <div class="item active">
                <img src="img/Shotscreen1.png">
                <div class="carousel-caption">
                  View Countdowns for all your projects
                </div>
              </div>
              <div class="item">
                <img src="img/ScreenShot2.png">
                <div class="carousel-caption">
                  
                </div>
              </div>
              <!--<div class="item">
                <img src="img/stock3.jpg">
                <div class="carousel-caption">
                  Photo #3 Caption
                </div>
              </div>-->
            </div> <!-- /.carousel-inner -->

            <a class="left carousel-control" href="#tour" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#tour" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div> <!-- /#tour -->
        </div> <!-- /#macbook -->
      </div> <!-- /.container -->
    </div> <!-- /#top.jumbotron -->

    
    <footer>
      <div class="container clearfix">
        <p class="pull-left">
          Copyright &copy; Deadline Countdown 2014
        </p>
        <p class="pull-right">
          
        </p>
      </div> <!-- /.container -->
    </footer>

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>
      $(".nav-link").click(function(e) {
        e.preventDefault();
        var link = $(this);
        var href = link.attr("href");
        $("html,body").animate({scrollTop: $(href).offset().top - 80}, 500);
        link.closest(".navbar").find(".navbar-toggle:not(.collapsed)").click();
      });
    </script>
  </body>
</html>